apiVersion: v1
kind: Namespace
metadata:
  name: drone
 
---
 
apiVersion: v1
kind: ServiceAccount
metadata:
  name: drone-deploy
  namespace: drone
automountServiceAccountToken: false
 
---
 
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: drone-deploy
  namespace: drone
rules:
  - apiGroups: ["extensions"]
    resources: ["deployments"]
    verbs: ["get","list","patch","update"]
 
---
 
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: drone-deploy
  namespace: drone
subjects:
  - kind: ServiceAccount
    name: drone-deploy
    namespace: drone
roleRef:
  kind: Role
  name: drone-deploy
  apiGroup: rbac.authorization.k8s.io